services:
  book-db:
    image: postgres:15-alpine
    container_name: book-db
    restart: always
    environment:
      - POSTGRES_DB=book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - library_backend

  book-service:
    build:
      context: book-service
      dockerfile: Dockerfile
    container_name: book-service
    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://book-db:5432/book
      - EXTERNAL_LIBRARY_URL=http://library-service:8081/api/v1/library
    depends_on:
      - book-db
    ports:
      - 8080:8080
    networks:
      - library_backend

  library-db:
    image: postgres:15-alpine
    container_name: library-db
    restart: always
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - library_backend

  library-service:
    build:
      context: library-service
      dockerfile: Dockerfile
    container_name: library-service
    restart: always
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/library
    depends_on:
      - library-db
    ports:
      - 8081:8081
    networks:
      - library_backend

networks:
  library_backend:
    driver: bridge
