services:
  book-service-db:
    image: postgres:15-alpine
    container_name: book-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
