server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/book
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

external:
  library:
    url: http://localhost:8081/api/v1/library

secret:
  key: hmjBzVJJ9epCnV7sYaL2hgrgsCMluQIO8osh/zThBl3iOAf0jfwdDU5dxFGfEgfd
  issuer: modsen
  expiration: 1800000 # 30 minutes
