server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/book
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

book:
  url: http://localhost:8080/api/v1/books

external:
  library:
    url: http://localhost:8081/api/v1/library